# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone SE",
  "iPhone 7",
  "iPhone 7 Plus",
  "iPad Retina",
  "iPad Air",
  "iPad Air 2",
  "iPad Pro (9.7 inch)",
  "iPad Pro (12.9 inch)",
])

languages([
  "en",
  "ja",
])

# The name of the scheme which contains the UI Tests
scheme "SampleIOSSnapshotUITests"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./SampleIOSSnapshot.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# snapshot --help
